---
 - hosts: dev-server
   tasks:
    - name: "Create new version folder"
      file:
        path: "{{ deployment_folder }}/{{ version }}"
        state: directory
      become: yes
      become_user: root  
    - name: "Copy new version files"
      copy: 
        src: .
        dest: "{{ deployment_folder }}/{{ version }}/"
        mode: 755
      notify: server_stop_start
      become: yes
      become_user: root
    - name: "Smoke test"
      uri: url=http://localhost:9000
      register: status
      ignore_errors: True
      become: yes
      become_user: root
    - name: "Success"
      command: cat "{{ version }}" > "{{ deployment_folder }}"/version
      when: status.status in [200,201,202,203]
      ignore_errors: True
      become: yes
      become_user: root
    - name: "Failure"
      command: cat "{{ deployment_folder }}"/version 
      register: version
      notify: server_stop_start    
      when: status.status not in [200,201,202,203]
      ignore_errors: True
      become: yes
      become_user: root
   handlers:
    - name: server_stop_start
      command: cat "{{ deployment_folder}}"/app.pid 
      register: pid
      notify: stop
      ignore_errors: true
      become: yes
      become_user: root
    - name: stop 
      command: kill {{ pid.stdout }}
      notify: start_new_version
      ignore_errors: true
      become: yes
      become_user: root
      notify: start_new_version
    - name: start_new_version
      command: cd "{{ deployment_folder }}/{{ version }}" && reaper.sh python app.py
      become: yes     
      become_user: root
  
